stages:
  - build

build:
  retry: 2
  tags:
    - python
  stage: build
  variables:
    COMMON_VERSION: 0.1.4
    NODE_ENV: production
    NODE_PATH: /home/ec2-user/node_modules
  script:
    - make build
  only:
    refs:
      - merge_request

buildnc:
  retry: 2
  tags:
    - python
  stage: build
  variables:
    COMMON_VERSION: 0.1.4
    NODE_ENV: production
    NODE_PATH: /home/ec2-user/node_modules
  script:
    - make buildnc
  only:
    refs:
      - master
