variables:
  GITLAB_USER: ci

before_script:
  - touch .env
  - make --version
  - docker --version
  - make docker-login

stages:
  - build
  - push

build:runner:
  tags:
    - builder
  stage: build
  script:
    - make buildci-runner
  only:
    refs:
      - merge_request
      - main

push:runner:
  tags:
    - linode
  stage: push
  script:
    - make pushci-runner
  only:
    refs:
      - main
