variables:
  NODE_ENV: production
  NODE_PATH: /home/trivialsec/node_modules
  NGINX_VERSION: 1.21.0
  GEO_DB_RELEASE: 2021-06
  MODSEC_BRANCH: v3.0.4
  OWASP_BRANCH: v3.3/master
  DOCKER_USER: ci
  RUNNER_TAGS: "python, docker"

before_script:
  - touch .env
  - make --version
  - docker --version
  - make docker-login

stages:
  - build
  - push

build:py:
  tags:
    - docker
  stage: build
  script:
    - make buildci-py
  only:
    refs:
      - merge_request
      - main

build:node:
  tags:
    - docker
  stage: build
  script:
    - make buildci-node
  only:
    refs:
      - merge_request
      - main

build:waf:
  tags:
    - builder
  stage: build
  script:
    - make buildci-waf
  only:
    refs:
      - merge_request
      - main

build:runner:
  tags:
    - docker
  stage: build
  script:
    - make buildci-runner
  only:
    refs:
      - merge_request
      - main

push:py:
  tags:
    - docker
  stage: push
  script:
    - make pushci-py
  only:
    refs:
      - main

push:node:
  tags:
    - docker
  stage: push
  script:
    - make pushci-node
  only:
    refs:
      - main

push:waf:
  tags:
    - docker
  stage: push
  script:
    - make pushci-waf
  only:
    refs:
      - main

push:runner:
  tags:
    - docker
  stage: push
  script:
    - make pushci-runner
  only:
    refs:
      - main
