variables:
  NODE_ENV: production
  NODE_PATH: /home/trivialsec/node_modules
  NGINX_VERSION: 1.21.0
  GEO_DB_RELEASE: 2021-06
  MODSEC_BRANCH: v3.0.4
  OWASP_BRANCH: v3.3/master
  DOCKER_USER: ci

before_script:
  - make --version
  - docker --version
  - docker-compose --version

stages:
  - build
  - push

build:
  retry: 2
  tags:
    - python
  stage: build
  script:
    - make buildci
  only:
    refs:
      - merge_request
      - main

push:
  retry: 2
  tags:
    - python
  stage: build
  script:
    - make docker-login
    - make push
  only:
    refs:
      - main
