image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  COMMON_VERSION: 0.1.4
  NODE_ENV: production
  NODE_PATH: /home/ec2-user/node_modules

before_script:
  - docker info
  - apk add --no-cache docker-compose

stages:
  - build

build:
  retry: 2
  tags:
    - python
  stage: build
  script:
    - make build
  only:
    refs:
      - merge_request

buildnc:
  retry: 2
  tags:
    - python
  stage: build
  script:
    - make buildnc
  only:
    refs:
      - master
