version: '3.6'
x-defaults: &defaults
  env_file: .env
  restart: unless-stopped
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  python:
    env_file: .env
    image: registry.gitlab.com/trivialsec/containers-common/python
    build:
      context: ./docker/python
      dockerfile: Dockerfile
      args:
        PYTHONUNBUFFERED: 1
        PYTHONUTF8: 1
        CFLAGS: '-O0'
        STATICBUILD: 1
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
  nodejs:
    env_file: .env
    image: registry.gitlab.com/trivialsec/containers-common/nodejs
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      network: host
      args:
        NODE_ENV: ${NODE_ENV}
        NODE_PATH: ${NODE_PATH}
  waf:
    env_file: .env
    image: registry.gitlab.com/trivialsec/containers-common/waf
    build:
      context: ./docker/waf
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        GEO_DB_RELEASE: ${GEO_DB_RELEASE}
        MODSEC_BRANCH: ${MODSEC_BRANCH}
        OWASP_BRANCH: ${OWASP_BRANCH}

  gitlab-runner:
    <<: *defaults
    image: registry.gitlab.com/trivialsec/containers-common/gitlab-runner
    build:
      context: ./docker/gitlab-runner
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - gitlab-cache:/cache:rw
    environment:
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_TAGS: ${RUNNER_TAGS}
      RUNNER_NAME: ${RUNNER_NAME}

  mysql:
    <<: *defaults
    image: docker.io/library/mysql:8
    container_name: mysql
    command: 'mysqld --bind-address=0.0.0.0'
    volumes:
      - mysql-datadir:/var/lib/mysql
      - ./sql:/tmp/sql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    security_opt:
      - seccomp:"./docker/seccomp-mysql.json"
    healthcheck:
      test: mysqladmin ping -h mysql
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - mysql
  
  redis:
    <<: *defaults
    image: docker.io/library/redis:5.0
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis-datadir:/data
    networks:
      default:
        aliases:
          - redis

volumes:
  redis-datadir:
    external: true
    name: redis-datadir
  mysql-datadir:
    external: true
    name: mysql-datadir
  gitlab-cache:
    external: true
    name: gitlab-cache

networks:
  default:
    external:
      name: trivialsec
