version: '3.9'
x-defaults: &defaults
  env_file: .env
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  gitlab-runner:
    <<: *defaults
    image: registry.gitlab.com/trivialsec/containers-common/gitlab-runner
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - gitlab-cache:/cache:rw
    environment:
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_TAGS: ${RUNNER_TAGS}
      RUNNER_NAME: ${RUNNER_NAME}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
      resources:
        limits:
          cpus: '2.00'
          memory: 2GB
        reservations:
          memory: 1GB

volumes:
  gitlab-cache:
    external: true
    name: gitlab-cache
