version: '3.9'
x-defaults: &defaults
  env_file: .env
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  python:
    env_file: .env
    image: registry.gitlab.com/trivialsec/containers-common/python
    build:
      context: ./docker/python
      dockerfile: Dockerfile
      args:
        PYTHONUNBUFFERED: 1
        PYTHONUTF8: 1
        CFLAGS: '-O0'
        STATICBUILD: 1
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
  nodejs:
    env_file: .env
    image: registry.gitlab.com/trivialsec/containers-common/nodejs
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      network: host
      args:
        NODE_ENV: ${NODE_ENV}
        NODE_PATH: ${NODE_PATH}
  waf:
    env_file: .env
    image: registry.gitlab.com/trivialsec/containers-common/waf
    build:
      context: ./docker/waf
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        GEO_DB_RELEASE: ${GEO_DB_RELEASE}
        MODSEC_BRANCH: ${MODSEC_BRANCH}
        OWASP_BRANCH: ${OWASP_BRANCH}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 500M

  gitlab-runner:
    <<: *defaults
    image: registry.gitlab.com/trivialsec/containers-common/gitlab-runner
    build:
      context: ./docker/gitlab-runner
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - gitlab-cache:/cache:rw
    environment:
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_TAGS: ${RUNNER_TAGS}
      RUNNER_NAME: ${RUNNER_NAME}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '2.00'
          memory: 2GB
        reservations:
          cpus: '1.00'
          memory: 1GB

  redis:
    <<: *defaults
    image: docker.io/library/redis:5.0
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis-datadir:/data
    networks:
      default:
        aliases:
          - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 500M

  elasticsearch:
    <<: *defaults
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    user: "1000:0"
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
    environment:
      ELASTIC_PASSWORD: "${ELASTIC_PASSWORD}"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./docker/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options.d/jvm.options
      - ./docker/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker/elasticsearch/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    networks:
      default:
        aliases:
          - elasticsearch
          - es
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '1.00'
          memory: 2GB
        reservations:
          cpus: '1.00'
          memory: 1.5GB

volumes:
  elasticsearch:
    external: true
    name: elasticsearch
  redis-datadir:
    external: true
    name: redis-datadir
  mysql-main:
    external: true
    name: mysql-main-data
  mysql-replica:
    external: true
    name: mysql-replica-data
  gitlab-cache:
    external: true
    name: gitlab-cache

networks:
  default:
    external:
      name: trivialsec
