version: '3.9'
x-defaults: &defaults
  env_file: .env
  logging:
    options:
      max-size: "10m"
      max-file: "3"

services:
  python:
    env_file: .env
    image: registry.gitlab.com/trivialsec/containers-common/python
    build:
      context: ./docker/python
      dockerfile: Dockerfile
      args:
        PYTHONUNBUFFERED: 1
        PYTHONUTF8: 1
        CFLAGS: '-O0'
        STATICBUILD: 1
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
  nodejs:
    env_file: .env
    image: registry.gitlab.com/trivialsec/containers-common/nodejs
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      network: host
      args:
        NODE_ENV: ${NODE_ENV}
        NODE_PATH: ${NODE_PATH}
  waf:
    env_file: .env
    image: registry.gitlab.com/trivialsec/containers-common/waf
    build:
      context: ./docker/waf
      dockerfile: Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        GEO_DB_RELEASE: ${GEO_DB_RELEASE}
        MODSEC_BRANCH: ${MODSEC_BRANCH}
        OWASP_BRANCH: ${OWASP_BRANCH}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 500M

  gitlab-runner:
    <<: *defaults
    image: registry.gitlab.com/trivialsec/containers-common/gitlab-runner
    build:
      context: ./docker/gitlab-runner
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - gitlab-cache:/cache:rw
    environment:
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_TAGS: ${RUNNER_TAGS}
      RUNNER_NAME: ${RUNNER_NAME}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '2.00'
          memory: 2GB
        reservations:
          cpus: '1.00'
          memory: 1GB

  mysql-replica:
    <<: *defaults
    image: docker.io/library/mysql:8
    container_name: mysql-replica
    hostname: mysql-replica
    command: 'mysqld --bind-address=0.0.0.0'
    volumes:
      - mysql-replica:/var/lib/mysql
      - ./docker/mysql/replica.cnf:/etc/mysql/conf.d/replica.cnf
    ports:
      - 33306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_REPLICA_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    security_opt:
      - seccomp:"./docker/seccomp-mysql.json"
    healthcheck:
      test: mysqladmin ping -h mysql
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - mysql-replica
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 500M

  mysql-main:
    <<: *defaults
    image: docker.io/library/mysql:8
    container_name: mysql-main
    hostname: mysql-main
    command: 'mysqld --bind-address=0.0.0.0'
    volumes:
      - mysql-main:/var/lib/mysql
      - ./docker/mysql/main.cnf:/etc/mysql/conf.d/main.cnf
      - ./sql:/tmp/sql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_MAIN_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    security_opt:
      - seccomp:"./docker/seccomp-mysql.json"
    healthcheck:
      test: mysqladmin ping -h mysql
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - mysql-main
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 500M

  redis:
    <<: *defaults
    image: docker.io/library/redis:5.0
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    volumes:
      - redis-datadir:/data
    networks:
      default:
        aliases:
          - redis
    deploy:
      restart_policy:
        condition: on-failure
        delay: 0s
        max_attempts: 10
        window: 3s
      resources:
        limits:
          cpus: '1.00'
          memory: 1GB
        reservations:
          cpus: '0.50'
          memory: 500M

volumes:
  redis-datadir:
    external: true
    name: redis-datadir
  mysql-main:
    external: true
    name: mysql-main-data
  mysql-replica:
    external: true
    name: mysql-replica-data
  gitlab-cache:
    external: true
    name: gitlab-cache

networks:
  default:
    external:
      name: trivialsec
